/*
Readarr

Readarr API docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package readarr

import (
	"encoding/json"
	"time"
)

// EditionResource struct for EditionResource
type EditionResource struct {
	Id *int32 `json:"id,omitempty"`
	BookId *int32 `json:"bookId,omitempty"`
	ForeignEditionId NullableString `json:"foreignEditionId,omitempty"`
	TitleSlug NullableString `json:"titleSlug,omitempty"`
	Isbn13 NullableString `json:"isbn13,omitempty"`
	Asin NullableString `json:"asin,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Language NullableString `json:"language,omitempty"`
	Overview NullableString `json:"overview,omitempty"`
	Format NullableString `json:"format,omitempty"`
	IsEbook *bool `json:"isEbook,omitempty"`
	Disambiguation NullableString `json:"disambiguation,omitempty"`
	Publisher NullableString `json:"publisher,omitempty"`
	PageCount *int32 `json:"pageCount,omitempty"`
	ReleaseDate NullableTime `json:"releaseDate,omitempty"`
	Images []*MediaCover `json:"images,omitempty"`
	Links []*Links `json:"links,omitempty"`
	Ratings *Ratings `json:"ratings,omitempty"`
	Monitored *bool `json:"monitored,omitempty"`
	ManualAdd *bool `json:"manualAdd,omitempty"`
	RemoteCover NullableString `json:"remoteCover,omitempty"`
	Grabbed *bool `json:"grabbed,omitempty"`
}

// NewEditionResource instantiates a new EditionResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditionResource() *EditionResource {
	this := EditionResource{}
	return &this
}

// NewEditionResourceWithDefaults instantiates a new EditionResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditionResourceWithDefaults() *EditionResource {
	this := EditionResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EditionResource) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditionResource) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EditionResource) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *EditionResource) SetId(v int32) {
	o.Id = &v
}

// GetBookId returns the BookId field value if set, zero value otherwise.
func (o *EditionResource) GetBookId() int32 {
	if o == nil || isNil(o.BookId) {
		var ret int32
		return ret
	}
	return *o.BookId
}

// GetBookIdOk returns a tuple with the BookId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditionResource) GetBookIdOk() (*int32, bool) {
	if o == nil || isNil(o.BookId) {
    return nil, false
	}
	return o.BookId, true
}

// HasBookId returns a boolean if a field has been set.
func (o *EditionResource) HasBookId() bool {
	if o != nil && !isNil(o.BookId) {
		return true
	}

	return false
}

// SetBookId gets a reference to the given int32 and assigns it to the BookId field.
func (o *EditionResource) SetBookId(v int32) {
	o.BookId = &v
}

// GetForeignEditionId returns the ForeignEditionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetForeignEditionId() string {
	if o == nil || isNil(o.ForeignEditionId.Get()) {
		var ret string
		return ret
	}
	return *o.ForeignEditionId.Get()
}

// GetForeignEditionIdOk returns a tuple with the ForeignEditionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetForeignEditionIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.ForeignEditionId.Get(), o.ForeignEditionId.IsSet()
}

// HasForeignEditionId returns a boolean if a field has been set.
func (o *EditionResource) HasForeignEditionId() bool {
	if o != nil && o.ForeignEditionId.IsSet() {
		return true
	}

	return false
}

// SetForeignEditionId gets a reference to the given NullableString and assigns it to the ForeignEditionId field.
func (o *EditionResource) SetForeignEditionId(v string) {
	o.ForeignEditionId.Set(&v)
}
// SetForeignEditionIdNil sets the value for ForeignEditionId to be an explicit nil
func (o *EditionResource) SetForeignEditionIdNil() {
	o.ForeignEditionId.Set(nil)
}

// UnsetForeignEditionId ensures that no value is present for ForeignEditionId, not even an explicit nil
func (o *EditionResource) UnsetForeignEditionId() {
	o.ForeignEditionId.Unset()
}

// GetTitleSlug returns the TitleSlug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetTitleSlug() string {
	if o == nil || isNil(o.TitleSlug.Get()) {
		var ret string
		return ret
	}
	return *o.TitleSlug.Get()
}

// GetTitleSlugOk returns a tuple with the TitleSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetTitleSlugOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.TitleSlug.Get(), o.TitleSlug.IsSet()
}

// HasTitleSlug returns a boolean if a field has been set.
func (o *EditionResource) HasTitleSlug() bool {
	if o != nil && o.TitleSlug.IsSet() {
		return true
	}

	return false
}

// SetTitleSlug gets a reference to the given NullableString and assigns it to the TitleSlug field.
func (o *EditionResource) SetTitleSlug(v string) {
	o.TitleSlug.Set(&v)
}
// SetTitleSlugNil sets the value for TitleSlug to be an explicit nil
func (o *EditionResource) SetTitleSlugNil() {
	o.TitleSlug.Set(nil)
}

// UnsetTitleSlug ensures that no value is present for TitleSlug, not even an explicit nil
func (o *EditionResource) UnsetTitleSlug() {
	o.TitleSlug.Unset()
}

// GetIsbn13 returns the Isbn13 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetIsbn13() string {
	if o == nil || isNil(o.Isbn13.Get()) {
		var ret string
		return ret
	}
	return *o.Isbn13.Get()
}

// GetIsbn13Ok returns a tuple with the Isbn13 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetIsbn13Ok() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Isbn13.Get(), o.Isbn13.IsSet()
}

// HasIsbn13 returns a boolean if a field has been set.
func (o *EditionResource) HasIsbn13() bool {
	if o != nil && o.Isbn13.IsSet() {
		return true
	}

	return false
}

// SetIsbn13 gets a reference to the given NullableString and assigns it to the Isbn13 field.
func (o *EditionResource) SetIsbn13(v string) {
	o.Isbn13.Set(&v)
}
// SetIsbn13Nil sets the value for Isbn13 to be an explicit nil
func (o *EditionResource) SetIsbn13Nil() {
	o.Isbn13.Set(nil)
}

// UnsetIsbn13 ensures that no value is present for Isbn13, not even an explicit nil
func (o *EditionResource) UnsetIsbn13() {
	o.Isbn13.Unset()
}

// GetAsin returns the Asin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetAsin() string {
	if o == nil || isNil(o.Asin.Get()) {
		var ret string
		return ret
	}
	return *o.Asin.Get()
}

// GetAsinOk returns a tuple with the Asin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetAsinOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Asin.Get(), o.Asin.IsSet()
}

// HasAsin returns a boolean if a field has been set.
func (o *EditionResource) HasAsin() bool {
	if o != nil && o.Asin.IsSet() {
		return true
	}

	return false
}

// SetAsin gets a reference to the given NullableString and assigns it to the Asin field.
func (o *EditionResource) SetAsin(v string) {
	o.Asin.Set(&v)
}
// SetAsinNil sets the value for Asin to be an explicit nil
func (o *EditionResource) SetAsinNil() {
	o.Asin.Set(nil)
}

// UnsetAsin ensures that no value is present for Asin, not even an explicit nil
func (o *EditionResource) UnsetAsin() {
	o.Asin.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetTitle() string {
	if o == nil || isNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetTitleOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *EditionResource) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *EditionResource) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *EditionResource) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *EditionResource) UnsetTitle() {
	o.Title.Unset()
}

// GetLanguage returns the Language field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetLanguage() string {
	if o == nil || isNil(o.Language.Get()) {
		var ret string
		return ret
	}
	return *o.Language.Get()
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetLanguageOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Language.Get(), o.Language.IsSet()
}

// HasLanguage returns a boolean if a field has been set.
func (o *EditionResource) HasLanguage() bool {
	if o != nil && o.Language.IsSet() {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given NullableString and assigns it to the Language field.
func (o *EditionResource) SetLanguage(v string) {
	o.Language.Set(&v)
}
// SetLanguageNil sets the value for Language to be an explicit nil
func (o *EditionResource) SetLanguageNil() {
	o.Language.Set(nil)
}

// UnsetLanguage ensures that no value is present for Language, not even an explicit nil
func (o *EditionResource) UnsetLanguage() {
	o.Language.Unset()
}

// GetOverview returns the Overview field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetOverview() string {
	if o == nil || isNil(o.Overview.Get()) {
		var ret string
		return ret
	}
	return *o.Overview.Get()
}

// GetOverviewOk returns a tuple with the Overview field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetOverviewOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Overview.Get(), o.Overview.IsSet()
}

// HasOverview returns a boolean if a field has been set.
func (o *EditionResource) HasOverview() bool {
	if o != nil && o.Overview.IsSet() {
		return true
	}

	return false
}

// SetOverview gets a reference to the given NullableString and assigns it to the Overview field.
func (o *EditionResource) SetOverview(v string) {
	o.Overview.Set(&v)
}
// SetOverviewNil sets the value for Overview to be an explicit nil
func (o *EditionResource) SetOverviewNil() {
	o.Overview.Set(nil)
}

// UnsetOverview ensures that no value is present for Overview, not even an explicit nil
func (o *EditionResource) UnsetOverview() {
	o.Overview.Unset()
}

// GetFormat returns the Format field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetFormat() string {
	if o == nil || isNil(o.Format.Get()) {
		var ret string
		return ret
	}
	return *o.Format.Get()
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetFormatOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Format.Get(), o.Format.IsSet()
}

// HasFormat returns a boolean if a field has been set.
func (o *EditionResource) HasFormat() bool {
	if o != nil && o.Format.IsSet() {
		return true
	}

	return false
}

// SetFormat gets a reference to the given NullableString and assigns it to the Format field.
func (o *EditionResource) SetFormat(v string) {
	o.Format.Set(&v)
}
// SetFormatNil sets the value for Format to be an explicit nil
func (o *EditionResource) SetFormatNil() {
	o.Format.Set(nil)
}

// UnsetFormat ensures that no value is present for Format, not even an explicit nil
func (o *EditionResource) UnsetFormat() {
	o.Format.Unset()
}

// GetIsEbook returns the IsEbook field value if set, zero value otherwise.
func (o *EditionResource) GetIsEbook() bool {
	if o == nil || isNil(o.IsEbook) {
		var ret bool
		return ret
	}
	return *o.IsEbook
}

// GetIsEbookOk returns a tuple with the IsEbook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditionResource) GetIsEbookOk() (*bool, bool) {
	if o == nil || isNil(o.IsEbook) {
    return nil, false
	}
	return o.IsEbook, true
}

// HasIsEbook returns a boolean if a field has been set.
func (o *EditionResource) HasIsEbook() bool {
	if o != nil && !isNil(o.IsEbook) {
		return true
	}

	return false
}

// SetIsEbook gets a reference to the given bool and assigns it to the IsEbook field.
func (o *EditionResource) SetIsEbook(v bool) {
	o.IsEbook = &v
}

// GetDisambiguation returns the Disambiguation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetDisambiguation() string {
	if o == nil || isNil(o.Disambiguation.Get()) {
		var ret string
		return ret
	}
	return *o.Disambiguation.Get()
}

// GetDisambiguationOk returns a tuple with the Disambiguation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetDisambiguationOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Disambiguation.Get(), o.Disambiguation.IsSet()
}

// HasDisambiguation returns a boolean if a field has been set.
func (o *EditionResource) HasDisambiguation() bool {
	if o != nil && o.Disambiguation.IsSet() {
		return true
	}

	return false
}

// SetDisambiguation gets a reference to the given NullableString and assigns it to the Disambiguation field.
func (o *EditionResource) SetDisambiguation(v string) {
	o.Disambiguation.Set(&v)
}
// SetDisambiguationNil sets the value for Disambiguation to be an explicit nil
func (o *EditionResource) SetDisambiguationNil() {
	o.Disambiguation.Set(nil)
}

// UnsetDisambiguation ensures that no value is present for Disambiguation, not even an explicit nil
func (o *EditionResource) UnsetDisambiguation() {
	o.Disambiguation.Unset()
}

// GetPublisher returns the Publisher field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetPublisher() string {
	if o == nil || isNil(o.Publisher.Get()) {
		var ret string
		return ret
	}
	return *o.Publisher.Get()
}

// GetPublisherOk returns a tuple with the Publisher field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetPublisherOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Publisher.Get(), o.Publisher.IsSet()
}

// HasPublisher returns a boolean if a field has been set.
func (o *EditionResource) HasPublisher() bool {
	if o != nil && o.Publisher.IsSet() {
		return true
	}

	return false
}

// SetPublisher gets a reference to the given NullableString and assigns it to the Publisher field.
func (o *EditionResource) SetPublisher(v string) {
	o.Publisher.Set(&v)
}
// SetPublisherNil sets the value for Publisher to be an explicit nil
func (o *EditionResource) SetPublisherNil() {
	o.Publisher.Set(nil)
}

// UnsetPublisher ensures that no value is present for Publisher, not even an explicit nil
func (o *EditionResource) UnsetPublisher() {
	o.Publisher.Unset()
}

// GetPageCount returns the PageCount field value if set, zero value otherwise.
func (o *EditionResource) GetPageCount() int32 {
	if o == nil || isNil(o.PageCount) {
		var ret int32
		return ret
	}
	return *o.PageCount
}

// GetPageCountOk returns a tuple with the PageCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditionResource) GetPageCountOk() (*int32, bool) {
	if o == nil || isNil(o.PageCount) {
    return nil, false
	}
	return o.PageCount, true
}

// HasPageCount returns a boolean if a field has been set.
func (o *EditionResource) HasPageCount() bool {
	if o != nil && !isNil(o.PageCount) {
		return true
	}

	return false
}

// SetPageCount gets a reference to the given int32 and assigns it to the PageCount field.
func (o *EditionResource) SetPageCount(v int32) {
	o.PageCount = &v
}

// GetReleaseDate returns the ReleaseDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetReleaseDate() time.Time {
	if o == nil || isNil(o.ReleaseDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ReleaseDate.Get()
}

// GetReleaseDateOk returns a tuple with the ReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetReleaseDateOk() (*time.Time, bool) {
	if o == nil {
    return nil, false
	}
	return o.ReleaseDate.Get(), o.ReleaseDate.IsSet()
}

// HasReleaseDate returns a boolean if a field has been set.
func (o *EditionResource) HasReleaseDate() bool {
	if o != nil && o.ReleaseDate.IsSet() {
		return true
	}

	return false
}

// SetReleaseDate gets a reference to the given NullableTime and assigns it to the ReleaseDate field.
func (o *EditionResource) SetReleaseDate(v time.Time) {
	o.ReleaseDate.Set(&v)
}
// SetReleaseDateNil sets the value for ReleaseDate to be an explicit nil
func (o *EditionResource) SetReleaseDateNil() {
	o.ReleaseDate.Set(nil)
}

// UnsetReleaseDate ensures that no value is present for ReleaseDate, not even an explicit nil
func (o *EditionResource) UnsetReleaseDate() {
	o.ReleaseDate.Unset()
}

// GetImages returns the Images field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetImages() []*MediaCover {
	if o == nil {
		var ret []*MediaCover
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetImagesOk() ([]*MediaCover, bool) {
	if o == nil || isNil(o.Images) {
    return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *EditionResource) HasImages() bool {
	if o != nil && isNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []MediaCover and assigns it to the Images field.
func (o *EditionResource) SetImages(v []*MediaCover) {
	o.Images = v
}

// GetLinks returns the Links field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetLinks() []*Links {
	if o == nil {
		var ret []*Links
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetLinksOk() ([]*Links, bool) {
	if o == nil || isNil(o.Links) {
    return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *EditionResource) HasLinks() bool {
	if o != nil && isNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []Links and assigns it to the Links field.
func (o *EditionResource) SetLinks(v []*Links) {
	o.Links = v
}

// GetRatings returns the Ratings field value if set, zero value otherwise.
func (o *EditionResource) GetRatings() Ratings {
	if o == nil || isNil(o.Ratings) {
		var ret Ratings
		return ret
	}
	return *o.Ratings
}

// GetRatingsOk returns a tuple with the Ratings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditionResource) GetRatingsOk() (*Ratings, bool) {
	if o == nil || isNil(o.Ratings) {
    return nil, false
	}
	return o.Ratings, true
}

// HasRatings returns a boolean if a field has been set.
func (o *EditionResource) HasRatings() bool {
	if o != nil && !isNil(o.Ratings) {
		return true
	}

	return false
}

// SetRatings gets a reference to the given Ratings and assigns it to the Ratings field.
func (o *EditionResource) SetRatings(v Ratings) {
	o.Ratings = &v
}

// GetMonitored returns the Monitored field value if set, zero value otherwise.
func (o *EditionResource) GetMonitored() bool {
	if o == nil || isNil(o.Monitored) {
		var ret bool
		return ret
	}
	return *o.Monitored
}

// GetMonitoredOk returns a tuple with the Monitored field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditionResource) GetMonitoredOk() (*bool, bool) {
	if o == nil || isNil(o.Monitored) {
    return nil, false
	}
	return o.Monitored, true
}

// HasMonitored returns a boolean if a field has been set.
func (o *EditionResource) HasMonitored() bool {
	if o != nil && !isNil(o.Monitored) {
		return true
	}

	return false
}

// SetMonitored gets a reference to the given bool and assigns it to the Monitored field.
func (o *EditionResource) SetMonitored(v bool) {
	o.Monitored = &v
}

// GetManualAdd returns the ManualAdd field value if set, zero value otherwise.
func (o *EditionResource) GetManualAdd() bool {
	if o == nil || isNil(o.ManualAdd) {
		var ret bool
		return ret
	}
	return *o.ManualAdd
}

// GetManualAddOk returns a tuple with the ManualAdd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditionResource) GetManualAddOk() (*bool, bool) {
	if o == nil || isNil(o.ManualAdd) {
    return nil, false
	}
	return o.ManualAdd, true
}

// HasManualAdd returns a boolean if a field has been set.
func (o *EditionResource) HasManualAdd() bool {
	if o != nil && !isNil(o.ManualAdd) {
		return true
	}

	return false
}

// SetManualAdd gets a reference to the given bool and assigns it to the ManualAdd field.
func (o *EditionResource) SetManualAdd(v bool) {
	o.ManualAdd = &v
}

// GetRemoteCover returns the RemoteCover field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditionResource) GetRemoteCover() string {
	if o == nil || isNil(o.RemoteCover.Get()) {
		var ret string
		return ret
	}
	return *o.RemoteCover.Get()
}

// GetRemoteCoverOk returns a tuple with the RemoteCover field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditionResource) GetRemoteCoverOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.RemoteCover.Get(), o.RemoteCover.IsSet()
}

// HasRemoteCover returns a boolean if a field has been set.
func (o *EditionResource) HasRemoteCover() bool {
	if o != nil && o.RemoteCover.IsSet() {
		return true
	}

	return false
}

// SetRemoteCover gets a reference to the given NullableString and assigns it to the RemoteCover field.
func (o *EditionResource) SetRemoteCover(v string) {
	o.RemoteCover.Set(&v)
}
// SetRemoteCoverNil sets the value for RemoteCover to be an explicit nil
func (o *EditionResource) SetRemoteCoverNil() {
	o.RemoteCover.Set(nil)
}

// UnsetRemoteCover ensures that no value is present for RemoteCover, not even an explicit nil
func (o *EditionResource) UnsetRemoteCover() {
	o.RemoteCover.Unset()
}

// GetGrabbed returns the Grabbed field value if set, zero value otherwise.
func (o *EditionResource) GetGrabbed() bool {
	if o == nil || isNil(o.Grabbed) {
		var ret bool
		return ret
	}
	return *o.Grabbed
}

// GetGrabbedOk returns a tuple with the Grabbed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditionResource) GetGrabbedOk() (*bool, bool) {
	if o == nil || isNil(o.Grabbed) {
    return nil, false
	}
	return o.Grabbed, true
}

// HasGrabbed returns a boolean if a field has been set.
func (o *EditionResource) HasGrabbed() bool {
	if o != nil && !isNil(o.Grabbed) {
		return true
	}

	return false
}

// SetGrabbed gets a reference to the given bool and assigns it to the Grabbed field.
func (o *EditionResource) SetGrabbed(v bool) {
	o.Grabbed = &v
}

func (o EditionResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.BookId) {
		toSerialize["bookId"] = o.BookId
	}
	if o.ForeignEditionId.IsSet() {
		toSerialize["foreignEditionId"] = o.ForeignEditionId.Get()
	}
	if o.TitleSlug.IsSet() {
		toSerialize["titleSlug"] = o.TitleSlug.Get()
	}
	if o.Isbn13.IsSet() {
		toSerialize["isbn13"] = o.Isbn13.Get()
	}
	if o.Asin.IsSet() {
		toSerialize["asin"] = o.Asin.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Language.IsSet() {
		toSerialize["language"] = o.Language.Get()
	}
	if o.Overview.IsSet() {
		toSerialize["overview"] = o.Overview.Get()
	}
	if o.Format.IsSet() {
		toSerialize["format"] = o.Format.Get()
	}
	if !isNil(o.IsEbook) {
		toSerialize["isEbook"] = o.IsEbook
	}
	if o.Disambiguation.IsSet() {
		toSerialize["disambiguation"] = o.Disambiguation.Get()
	}
	if o.Publisher.IsSet() {
		toSerialize["publisher"] = o.Publisher.Get()
	}
	if !isNil(o.PageCount) {
		toSerialize["pageCount"] = o.PageCount
	}
	if o.ReleaseDate.IsSet() {
		toSerialize["releaseDate"] = o.ReleaseDate.Get()
	}
	if o.Images != nil {
		toSerialize["images"] = o.Images
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if !isNil(o.Ratings) {
		toSerialize["ratings"] = o.Ratings
	}
	if !isNil(o.Monitored) {
		toSerialize["monitored"] = o.Monitored
	}
	if !isNil(o.ManualAdd) {
		toSerialize["manualAdd"] = o.ManualAdd
	}
	if o.RemoteCover.IsSet() {
		toSerialize["remoteCover"] = o.RemoteCover.Get()
	}
	if !isNil(o.Grabbed) {
		toSerialize["grabbed"] = o.Grabbed
	}
	return json.Marshal(toSerialize)
}

type NullableEditionResource struct {
	value *EditionResource
	isSet bool
}

func (v NullableEditionResource) Get() *EditionResource {
	return v.value
}

func (v *NullableEditionResource) Set(val *EditionResource) {
	v.value = val
	v.isSet = true
}

func (v NullableEditionResource) IsSet() bool {
	return v.isSet
}

func (v *NullableEditionResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditionResource(val *EditionResource) *NullableEditionResource {
	return &NullableEditionResource{value: val, isSet: true}
}

func (v NullableEditionResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditionResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


