/*
Readarr

Readarr API docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package readarr

import (
	"encoding/json"
	"time"
)

// ReleaseResource struct for ReleaseResource
type ReleaseResource struct {
	Id *int32 `json:"id,omitempty"`
	Guid NullableString `json:"guid,omitempty"`
	Quality *QualityModel `json:"quality,omitempty"`
	QualityWeight *int32 `json:"qualityWeight,omitempty"`
	Age *int32 `json:"age,omitempty"`
	AgeHours *float64 `json:"ageHours,omitempty"`
	AgeMinutes *float64 `json:"ageMinutes,omitempty"`
	Size *int64 `json:"size,omitempty"`
	IndexerId *int32 `json:"indexerId,omitempty"`
	Indexer NullableString `json:"indexer,omitempty"`
	ReleaseGroup NullableString `json:"releaseGroup,omitempty"`
	SubGroup NullableString `json:"subGroup,omitempty"`
	ReleaseHash NullableString `json:"releaseHash,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Discography *bool `json:"discography,omitempty"`
	SceneSource *bool `json:"sceneSource,omitempty"`
	AirDate NullableString `json:"airDate,omitempty"`
	AuthorName NullableString `json:"authorName,omitempty"`
	BookTitle NullableString `json:"bookTitle,omitempty"`
	Approved *bool `json:"approved,omitempty"`
	TemporarilyRejected *bool `json:"temporarilyRejected,omitempty"`
	Rejected *bool `json:"rejected,omitempty"`
	Rejections []*string `json:"rejections,omitempty"`
	PublishDate *time.Time `json:"publishDate,omitempty"`
	CommentUrl NullableString `json:"commentUrl,omitempty"`
	DownloadUrl NullableString `json:"downloadUrl,omitempty"`
	InfoUrl NullableString `json:"infoUrl,omitempty"`
	DownloadAllowed *bool `json:"downloadAllowed,omitempty"`
	ReleaseWeight *int32 `json:"releaseWeight,omitempty"`
	CustomFormats []*CustomFormatResource `json:"customFormats,omitempty"`
	CustomFormatScore *int32 `json:"customFormatScore,omitempty"`
	MagnetUrl NullableString `json:"magnetUrl,omitempty"`
	InfoHash NullableString `json:"infoHash,omitempty"`
	Seeders NullableInt32 `json:"seeders,omitempty"`
	Leechers NullableInt32 `json:"leechers,omitempty"`
	Protocol *DownloadProtocol `json:"protocol,omitempty"`
	AuthorId NullableInt32 `json:"authorId,omitempty"`
	BookId NullableInt32 `json:"bookId,omitempty"`
	DownloadClientId NullableInt32 `json:"downloadClientId,omitempty"`
	DownloadClient NullableString `json:"downloadClient,omitempty"`
}

// NewReleaseResource instantiates a new ReleaseResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReleaseResource() *ReleaseResource {
	this := ReleaseResource{}
	return &this
}

// NewReleaseResourceWithDefaults instantiates a new ReleaseResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReleaseResourceWithDefaults() *ReleaseResource {
	this := ReleaseResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReleaseResource) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReleaseResource) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ReleaseResource) SetId(v int32) {
	o.Id = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetGuid() string {
	if o == nil || isNil(o.Guid.Get()) {
		var ret string
		return ret
	}
	return *o.Guid.Get()
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetGuidOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Guid.Get(), o.Guid.IsSet()
}

// HasGuid returns a boolean if a field has been set.
func (o *ReleaseResource) HasGuid() bool {
	if o != nil && o.Guid.IsSet() {
		return true
	}

	return false
}

// SetGuid gets a reference to the given NullableString and assigns it to the Guid field.
func (o *ReleaseResource) SetGuid(v string) {
	o.Guid.Set(&v)
}
// SetGuidNil sets the value for Guid to be an explicit nil
func (o *ReleaseResource) SetGuidNil() {
	o.Guid.Set(nil)
}

// UnsetGuid ensures that no value is present for Guid, not even an explicit nil
func (o *ReleaseResource) UnsetGuid() {
	o.Guid.Unset()
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *ReleaseResource) GetQuality() QualityModel {
	if o == nil || isNil(o.Quality) {
		var ret QualityModel
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetQualityOk() (*QualityModel, bool) {
	if o == nil || isNil(o.Quality) {
    return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *ReleaseResource) HasQuality() bool {
	if o != nil && !isNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given QualityModel and assigns it to the Quality field.
func (o *ReleaseResource) SetQuality(v QualityModel) {
	o.Quality = &v
}

// GetQualityWeight returns the QualityWeight field value if set, zero value otherwise.
func (o *ReleaseResource) GetQualityWeight() int32 {
	if o == nil || isNil(o.QualityWeight) {
		var ret int32
		return ret
	}
	return *o.QualityWeight
}

// GetQualityWeightOk returns a tuple with the QualityWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetQualityWeightOk() (*int32, bool) {
	if o == nil || isNil(o.QualityWeight) {
    return nil, false
	}
	return o.QualityWeight, true
}

// HasQualityWeight returns a boolean if a field has been set.
func (o *ReleaseResource) HasQualityWeight() bool {
	if o != nil && !isNil(o.QualityWeight) {
		return true
	}

	return false
}

// SetQualityWeight gets a reference to the given int32 and assigns it to the QualityWeight field.
func (o *ReleaseResource) SetQualityWeight(v int32) {
	o.QualityWeight = &v
}

// GetAge returns the Age field value if set, zero value otherwise.
func (o *ReleaseResource) GetAge() int32 {
	if o == nil || isNil(o.Age) {
		var ret int32
		return ret
	}
	return *o.Age
}

// GetAgeOk returns a tuple with the Age field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetAgeOk() (*int32, bool) {
	if o == nil || isNil(o.Age) {
    return nil, false
	}
	return o.Age, true
}

// HasAge returns a boolean if a field has been set.
func (o *ReleaseResource) HasAge() bool {
	if o != nil && !isNil(o.Age) {
		return true
	}

	return false
}

// SetAge gets a reference to the given int32 and assigns it to the Age field.
func (o *ReleaseResource) SetAge(v int32) {
	o.Age = &v
}

// GetAgeHours returns the AgeHours field value if set, zero value otherwise.
func (o *ReleaseResource) GetAgeHours() float64 {
	if o == nil || isNil(o.AgeHours) {
		var ret float64
		return ret
	}
	return *o.AgeHours
}

// GetAgeHoursOk returns a tuple with the AgeHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetAgeHoursOk() (*float64, bool) {
	if o == nil || isNil(o.AgeHours) {
    return nil, false
	}
	return o.AgeHours, true
}

// HasAgeHours returns a boolean if a field has been set.
func (o *ReleaseResource) HasAgeHours() bool {
	if o != nil && !isNil(o.AgeHours) {
		return true
	}

	return false
}

// SetAgeHours gets a reference to the given float64 and assigns it to the AgeHours field.
func (o *ReleaseResource) SetAgeHours(v float64) {
	o.AgeHours = &v
}

// GetAgeMinutes returns the AgeMinutes field value if set, zero value otherwise.
func (o *ReleaseResource) GetAgeMinutes() float64 {
	if o == nil || isNil(o.AgeMinutes) {
		var ret float64
		return ret
	}
	return *o.AgeMinutes
}

// GetAgeMinutesOk returns a tuple with the AgeMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetAgeMinutesOk() (*float64, bool) {
	if o == nil || isNil(o.AgeMinutes) {
    return nil, false
	}
	return o.AgeMinutes, true
}

// HasAgeMinutes returns a boolean if a field has been set.
func (o *ReleaseResource) HasAgeMinutes() bool {
	if o != nil && !isNil(o.AgeMinutes) {
		return true
	}

	return false
}

// SetAgeMinutes gets a reference to the given float64 and assigns it to the AgeMinutes field.
func (o *ReleaseResource) SetAgeMinutes(v float64) {
	o.AgeMinutes = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ReleaseResource) GetSize() int64 {
	if o == nil || isNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetSizeOk() (*int64, bool) {
	if o == nil || isNil(o.Size) {
    return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ReleaseResource) HasSize() bool {
	if o != nil && !isNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *ReleaseResource) SetSize(v int64) {
	o.Size = &v
}

// GetIndexerId returns the IndexerId field value if set, zero value otherwise.
func (o *ReleaseResource) GetIndexerId() int32 {
	if o == nil || isNil(o.IndexerId) {
		var ret int32
		return ret
	}
	return *o.IndexerId
}

// GetIndexerIdOk returns a tuple with the IndexerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetIndexerIdOk() (*int32, bool) {
	if o == nil || isNil(o.IndexerId) {
    return nil, false
	}
	return o.IndexerId, true
}

// HasIndexerId returns a boolean if a field has been set.
func (o *ReleaseResource) HasIndexerId() bool {
	if o != nil && !isNil(o.IndexerId) {
		return true
	}

	return false
}

// SetIndexerId gets a reference to the given int32 and assigns it to the IndexerId field.
func (o *ReleaseResource) SetIndexerId(v int32) {
	o.IndexerId = &v
}

// GetIndexer returns the Indexer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetIndexer() string {
	if o == nil || isNil(o.Indexer.Get()) {
		var ret string
		return ret
	}
	return *o.Indexer.Get()
}

// GetIndexerOk returns a tuple with the Indexer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetIndexerOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Indexer.Get(), o.Indexer.IsSet()
}

// HasIndexer returns a boolean if a field has been set.
func (o *ReleaseResource) HasIndexer() bool {
	if o != nil && o.Indexer.IsSet() {
		return true
	}

	return false
}

// SetIndexer gets a reference to the given NullableString and assigns it to the Indexer field.
func (o *ReleaseResource) SetIndexer(v string) {
	o.Indexer.Set(&v)
}
// SetIndexerNil sets the value for Indexer to be an explicit nil
func (o *ReleaseResource) SetIndexerNil() {
	o.Indexer.Set(nil)
}

// UnsetIndexer ensures that no value is present for Indexer, not even an explicit nil
func (o *ReleaseResource) UnsetIndexer() {
	o.Indexer.Unset()
}

// GetReleaseGroup returns the ReleaseGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetReleaseGroup() string {
	if o == nil || isNil(o.ReleaseGroup.Get()) {
		var ret string
		return ret
	}
	return *o.ReleaseGroup.Get()
}

// GetReleaseGroupOk returns a tuple with the ReleaseGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetReleaseGroupOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.ReleaseGroup.Get(), o.ReleaseGroup.IsSet()
}

// HasReleaseGroup returns a boolean if a field has been set.
func (o *ReleaseResource) HasReleaseGroup() bool {
	if o != nil && o.ReleaseGroup.IsSet() {
		return true
	}

	return false
}

// SetReleaseGroup gets a reference to the given NullableString and assigns it to the ReleaseGroup field.
func (o *ReleaseResource) SetReleaseGroup(v string) {
	o.ReleaseGroup.Set(&v)
}
// SetReleaseGroupNil sets the value for ReleaseGroup to be an explicit nil
func (o *ReleaseResource) SetReleaseGroupNil() {
	o.ReleaseGroup.Set(nil)
}

// UnsetReleaseGroup ensures that no value is present for ReleaseGroup, not even an explicit nil
func (o *ReleaseResource) UnsetReleaseGroup() {
	o.ReleaseGroup.Unset()
}

// GetSubGroup returns the SubGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetSubGroup() string {
	if o == nil || isNil(o.SubGroup.Get()) {
		var ret string
		return ret
	}
	return *o.SubGroup.Get()
}

// GetSubGroupOk returns a tuple with the SubGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetSubGroupOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.SubGroup.Get(), o.SubGroup.IsSet()
}

// HasSubGroup returns a boolean if a field has been set.
func (o *ReleaseResource) HasSubGroup() bool {
	if o != nil && o.SubGroup.IsSet() {
		return true
	}

	return false
}

// SetSubGroup gets a reference to the given NullableString and assigns it to the SubGroup field.
func (o *ReleaseResource) SetSubGroup(v string) {
	o.SubGroup.Set(&v)
}
// SetSubGroupNil sets the value for SubGroup to be an explicit nil
func (o *ReleaseResource) SetSubGroupNil() {
	o.SubGroup.Set(nil)
}

// UnsetSubGroup ensures that no value is present for SubGroup, not even an explicit nil
func (o *ReleaseResource) UnsetSubGroup() {
	o.SubGroup.Unset()
}

// GetReleaseHash returns the ReleaseHash field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetReleaseHash() string {
	if o == nil || isNil(o.ReleaseHash.Get()) {
		var ret string
		return ret
	}
	return *o.ReleaseHash.Get()
}

// GetReleaseHashOk returns a tuple with the ReleaseHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetReleaseHashOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.ReleaseHash.Get(), o.ReleaseHash.IsSet()
}

// HasReleaseHash returns a boolean if a field has been set.
func (o *ReleaseResource) HasReleaseHash() bool {
	if o != nil && o.ReleaseHash.IsSet() {
		return true
	}

	return false
}

// SetReleaseHash gets a reference to the given NullableString and assigns it to the ReleaseHash field.
func (o *ReleaseResource) SetReleaseHash(v string) {
	o.ReleaseHash.Set(&v)
}
// SetReleaseHashNil sets the value for ReleaseHash to be an explicit nil
func (o *ReleaseResource) SetReleaseHashNil() {
	o.ReleaseHash.Set(nil)
}

// UnsetReleaseHash ensures that no value is present for ReleaseHash, not even an explicit nil
func (o *ReleaseResource) UnsetReleaseHash() {
	o.ReleaseHash.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetTitle() string {
	if o == nil || isNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetTitleOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *ReleaseResource) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *ReleaseResource) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *ReleaseResource) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *ReleaseResource) UnsetTitle() {
	o.Title.Unset()
}

// GetDiscography returns the Discography field value if set, zero value otherwise.
func (o *ReleaseResource) GetDiscography() bool {
	if o == nil || isNil(o.Discography) {
		var ret bool
		return ret
	}
	return *o.Discography
}

// GetDiscographyOk returns a tuple with the Discography field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetDiscographyOk() (*bool, bool) {
	if o == nil || isNil(o.Discography) {
    return nil, false
	}
	return o.Discography, true
}

// HasDiscography returns a boolean if a field has been set.
func (o *ReleaseResource) HasDiscography() bool {
	if o != nil && !isNil(o.Discography) {
		return true
	}

	return false
}

// SetDiscography gets a reference to the given bool and assigns it to the Discography field.
func (o *ReleaseResource) SetDiscography(v bool) {
	o.Discography = &v
}

// GetSceneSource returns the SceneSource field value if set, zero value otherwise.
func (o *ReleaseResource) GetSceneSource() bool {
	if o == nil || isNil(o.SceneSource) {
		var ret bool
		return ret
	}
	return *o.SceneSource
}

// GetSceneSourceOk returns a tuple with the SceneSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetSceneSourceOk() (*bool, bool) {
	if o == nil || isNil(o.SceneSource) {
    return nil, false
	}
	return o.SceneSource, true
}

// HasSceneSource returns a boolean if a field has been set.
func (o *ReleaseResource) HasSceneSource() bool {
	if o != nil && !isNil(o.SceneSource) {
		return true
	}

	return false
}

// SetSceneSource gets a reference to the given bool and assigns it to the SceneSource field.
func (o *ReleaseResource) SetSceneSource(v bool) {
	o.SceneSource = &v
}

// GetAirDate returns the AirDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetAirDate() string {
	if o == nil || isNil(o.AirDate.Get()) {
		var ret string
		return ret
	}
	return *o.AirDate.Get()
}

// GetAirDateOk returns a tuple with the AirDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetAirDateOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.AirDate.Get(), o.AirDate.IsSet()
}

// HasAirDate returns a boolean if a field has been set.
func (o *ReleaseResource) HasAirDate() bool {
	if o != nil && o.AirDate.IsSet() {
		return true
	}

	return false
}

// SetAirDate gets a reference to the given NullableString and assigns it to the AirDate field.
func (o *ReleaseResource) SetAirDate(v string) {
	o.AirDate.Set(&v)
}
// SetAirDateNil sets the value for AirDate to be an explicit nil
func (o *ReleaseResource) SetAirDateNil() {
	o.AirDate.Set(nil)
}

// UnsetAirDate ensures that no value is present for AirDate, not even an explicit nil
func (o *ReleaseResource) UnsetAirDate() {
	o.AirDate.Unset()
}

// GetAuthorName returns the AuthorName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetAuthorName() string {
	if o == nil || isNil(o.AuthorName.Get()) {
		var ret string
		return ret
	}
	return *o.AuthorName.Get()
}

// GetAuthorNameOk returns a tuple with the AuthorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetAuthorNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.AuthorName.Get(), o.AuthorName.IsSet()
}

// HasAuthorName returns a boolean if a field has been set.
func (o *ReleaseResource) HasAuthorName() bool {
	if o != nil && o.AuthorName.IsSet() {
		return true
	}

	return false
}

// SetAuthorName gets a reference to the given NullableString and assigns it to the AuthorName field.
func (o *ReleaseResource) SetAuthorName(v string) {
	o.AuthorName.Set(&v)
}
// SetAuthorNameNil sets the value for AuthorName to be an explicit nil
func (o *ReleaseResource) SetAuthorNameNil() {
	o.AuthorName.Set(nil)
}

// UnsetAuthorName ensures that no value is present for AuthorName, not even an explicit nil
func (o *ReleaseResource) UnsetAuthorName() {
	o.AuthorName.Unset()
}

// GetBookTitle returns the BookTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetBookTitle() string {
	if o == nil || isNil(o.BookTitle.Get()) {
		var ret string
		return ret
	}
	return *o.BookTitle.Get()
}

// GetBookTitleOk returns a tuple with the BookTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetBookTitleOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.BookTitle.Get(), o.BookTitle.IsSet()
}

// HasBookTitle returns a boolean if a field has been set.
func (o *ReleaseResource) HasBookTitle() bool {
	if o != nil && o.BookTitle.IsSet() {
		return true
	}

	return false
}

// SetBookTitle gets a reference to the given NullableString and assigns it to the BookTitle field.
func (o *ReleaseResource) SetBookTitle(v string) {
	o.BookTitle.Set(&v)
}
// SetBookTitleNil sets the value for BookTitle to be an explicit nil
func (o *ReleaseResource) SetBookTitleNil() {
	o.BookTitle.Set(nil)
}

// UnsetBookTitle ensures that no value is present for BookTitle, not even an explicit nil
func (o *ReleaseResource) UnsetBookTitle() {
	o.BookTitle.Unset()
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *ReleaseResource) GetApproved() bool {
	if o == nil || isNil(o.Approved) {
		var ret bool
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetApprovedOk() (*bool, bool) {
	if o == nil || isNil(o.Approved) {
    return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *ReleaseResource) HasApproved() bool {
	if o != nil && !isNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given bool and assigns it to the Approved field.
func (o *ReleaseResource) SetApproved(v bool) {
	o.Approved = &v
}

// GetTemporarilyRejected returns the TemporarilyRejected field value if set, zero value otherwise.
func (o *ReleaseResource) GetTemporarilyRejected() bool {
	if o == nil || isNil(o.TemporarilyRejected) {
		var ret bool
		return ret
	}
	return *o.TemporarilyRejected
}

// GetTemporarilyRejectedOk returns a tuple with the TemporarilyRejected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetTemporarilyRejectedOk() (*bool, bool) {
	if o == nil || isNil(o.TemporarilyRejected) {
    return nil, false
	}
	return o.TemporarilyRejected, true
}

// HasTemporarilyRejected returns a boolean if a field has been set.
func (o *ReleaseResource) HasTemporarilyRejected() bool {
	if o != nil && !isNil(o.TemporarilyRejected) {
		return true
	}

	return false
}

// SetTemporarilyRejected gets a reference to the given bool and assigns it to the TemporarilyRejected field.
func (o *ReleaseResource) SetTemporarilyRejected(v bool) {
	o.TemporarilyRejected = &v
}

// GetRejected returns the Rejected field value if set, zero value otherwise.
func (o *ReleaseResource) GetRejected() bool {
	if o == nil || isNil(o.Rejected) {
		var ret bool
		return ret
	}
	return *o.Rejected
}

// GetRejectedOk returns a tuple with the Rejected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetRejectedOk() (*bool, bool) {
	if o == nil || isNil(o.Rejected) {
    return nil, false
	}
	return o.Rejected, true
}

// HasRejected returns a boolean if a field has been set.
func (o *ReleaseResource) HasRejected() bool {
	if o != nil && !isNil(o.Rejected) {
		return true
	}

	return false
}

// SetRejected gets a reference to the given bool and assigns it to the Rejected field.
func (o *ReleaseResource) SetRejected(v bool) {
	o.Rejected = &v
}

// GetRejections returns the Rejections field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetRejections() []*string {
	if o == nil {
		var ret []*string
		return ret
	}
	return o.Rejections
}

// GetRejectionsOk returns a tuple with the Rejections field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetRejectionsOk() ([]*string, bool) {
	if o == nil || isNil(o.Rejections) {
    return nil, false
	}
	return o.Rejections, true
}

// HasRejections returns a boolean if a field has been set.
func (o *ReleaseResource) HasRejections() bool {
	if o != nil && isNil(o.Rejections) {
		return true
	}

	return false
}

// SetRejections gets a reference to the given []string and assigns it to the Rejections field.
func (o *ReleaseResource) SetRejections(v []*string) {
	o.Rejections = v
}

// GetPublishDate returns the PublishDate field value if set, zero value otherwise.
func (o *ReleaseResource) GetPublishDate() time.Time {
	if o == nil || isNil(o.PublishDate) {
		var ret time.Time
		return ret
	}
	return *o.PublishDate
}

// GetPublishDateOk returns a tuple with the PublishDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetPublishDateOk() (*time.Time, bool) {
	if o == nil || isNil(o.PublishDate) {
    return nil, false
	}
	return o.PublishDate, true
}

// HasPublishDate returns a boolean if a field has been set.
func (o *ReleaseResource) HasPublishDate() bool {
	if o != nil && !isNil(o.PublishDate) {
		return true
	}

	return false
}

// SetPublishDate gets a reference to the given time.Time and assigns it to the PublishDate field.
func (o *ReleaseResource) SetPublishDate(v time.Time) {
	o.PublishDate = &v
}

// GetCommentUrl returns the CommentUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetCommentUrl() string {
	if o == nil || isNil(o.CommentUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CommentUrl.Get()
}

// GetCommentUrlOk returns a tuple with the CommentUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetCommentUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.CommentUrl.Get(), o.CommentUrl.IsSet()
}

// HasCommentUrl returns a boolean if a field has been set.
func (o *ReleaseResource) HasCommentUrl() bool {
	if o != nil && o.CommentUrl.IsSet() {
		return true
	}

	return false
}

// SetCommentUrl gets a reference to the given NullableString and assigns it to the CommentUrl field.
func (o *ReleaseResource) SetCommentUrl(v string) {
	o.CommentUrl.Set(&v)
}
// SetCommentUrlNil sets the value for CommentUrl to be an explicit nil
func (o *ReleaseResource) SetCommentUrlNil() {
	o.CommentUrl.Set(nil)
}

// UnsetCommentUrl ensures that no value is present for CommentUrl, not even an explicit nil
func (o *ReleaseResource) UnsetCommentUrl() {
	o.CommentUrl.Unset()
}

// GetDownloadUrl returns the DownloadUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetDownloadUrl() string {
	if o == nil || isNil(o.DownloadUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DownloadUrl.Get()
}

// GetDownloadUrlOk returns a tuple with the DownloadUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetDownloadUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.DownloadUrl.Get(), o.DownloadUrl.IsSet()
}

// HasDownloadUrl returns a boolean if a field has been set.
func (o *ReleaseResource) HasDownloadUrl() bool {
	if o != nil && o.DownloadUrl.IsSet() {
		return true
	}

	return false
}

// SetDownloadUrl gets a reference to the given NullableString and assigns it to the DownloadUrl field.
func (o *ReleaseResource) SetDownloadUrl(v string) {
	o.DownloadUrl.Set(&v)
}
// SetDownloadUrlNil sets the value for DownloadUrl to be an explicit nil
func (o *ReleaseResource) SetDownloadUrlNil() {
	o.DownloadUrl.Set(nil)
}

// UnsetDownloadUrl ensures that no value is present for DownloadUrl, not even an explicit nil
func (o *ReleaseResource) UnsetDownloadUrl() {
	o.DownloadUrl.Unset()
}

// GetInfoUrl returns the InfoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetInfoUrl() string {
	if o == nil || isNil(o.InfoUrl.Get()) {
		var ret string
		return ret
	}
	return *o.InfoUrl.Get()
}

// GetInfoUrlOk returns a tuple with the InfoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetInfoUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.InfoUrl.Get(), o.InfoUrl.IsSet()
}

// HasInfoUrl returns a boolean if a field has been set.
func (o *ReleaseResource) HasInfoUrl() bool {
	if o != nil && o.InfoUrl.IsSet() {
		return true
	}

	return false
}

// SetInfoUrl gets a reference to the given NullableString and assigns it to the InfoUrl field.
func (o *ReleaseResource) SetInfoUrl(v string) {
	o.InfoUrl.Set(&v)
}
// SetInfoUrlNil sets the value for InfoUrl to be an explicit nil
func (o *ReleaseResource) SetInfoUrlNil() {
	o.InfoUrl.Set(nil)
}

// UnsetInfoUrl ensures that no value is present for InfoUrl, not even an explicit nil
func (o *ReleaseResource) UnsetInfoUrl() {
	o.InfoUrl.Unset()
}

// GetDownloadAllowed returns the DownloadAllowed field value if set, zero value otherwise.
func (o *ReleaseResource) GetDownloadAllowed() bool {
	if o == nil || isNil(o.DownloadAllowed) {
		var ret bool
		return ret
	}
	return *o.DownloadAllowed
}

// GetDownloadAllowedOk returns a tuple with the DownloadAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetDownloadAllowedOk() (*bool, bool) {
	if o == nil || isNil(o.DownloadAllowed) {
    return nil, false
	}
	return o.DownloadAllowed, true
}

// HasDownloadAllowed returns a boolean if a field has been set.
func (o *ReleaseResource) HasDownloadAllowed() bool {
	if o != nil && !isNil(o.DownloadAllowed) {
		return true
	}

	return false
}

// SetDownloadAllowed gets a reference to the given bool and assigns it to the DownloadAllowed field.
func (o *ReleaseResource) SetDownloadAllowed(v bool) {
	o.DownloadAllowed = &v
}

// GetReleaseWeight returns the ReleaseWeight field value if set, zero value otherwise.
func (o *ReleaseResource) GetReleaseWeight() int32 {
	if o == nil || isNil(o.ReleaseWeight) {
		var ret int32
		return ret
	}
	return *o.ReleaseWeight
}

// GetReleaseWeightOk returns a tuple with the ReleaseWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetReleaseWeightOk() (*int32, bool) {
	if o == nil || isNil(o.ReleaseWeight) {
    return nil, false
	}
	return o.ReleaseWeight, true
}

// HasReleaseWeight returns a boolean if a field has been set.
func (o *ReleaseResource) HasReleaseWeight() bool {
	if o != nil && !isNil(o.ReleaseWeight) {
		return true
	}

	return false
}

// SetReleaseWeight gets a reference to the given int32 and assigns it to the ReleaseWeight field.
func (o *ReleaseResource) SetReleaseWeight(v int32) {
	o.ReleaseWeight = &v
}

// GetCustomFormats returns the CustomFormats field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetCustomFormats() []*CustomFormatResource {
	if o == nil {
		var ret []*CustomFormatResource
		return ret
	}
	return o.CustomFormats
}

// GetCustomFormatsOk returns a tuple with the CustomFormats field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetCustomFormatsOk() ([]*CustomFormatResource, bool) {
	if o == nil || isNil(o.CustomFormats) {
    return nil, false
	}
	return o.CustomFormats, true
}

// HasCustomFormats returns a boolean if a field has been set.
func (o *ReleaseResource) HasCustomFormats() bool {
	if o != nil && isNil(o.CustomFormats) {
		return true
	}

	return false
}

// SetCustomFormats gets a reference to the given []CustomFormatResource and assigns it to the CustomFormats field.
func (o *ReleaseResource) SetCustomFormats(v []*CustomFormatResource) {
	o.CustomFormats = v
}

// GetCustomFormatScore returns the CustomFormatScore field value if set, zero value otherwise.
func (o *ReleaseResource) GetCustomFormatScore() int32 {
	if o == nil || isNil(o.CustomFormatScore) {
		var ret int32
		return ret
	}
	return *o.CustomFormatScore
}

// GetCustomFormatScoreOk returns a tuple with the CustomFormatScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetCustomFormatScoreOk() (*int32, bool) {
	if o == nil || isNil(o.CustomFormatScore) {
    return nil, false
	}
	return o.CustomFormatScore, true
}

// HasCustomFormatScore returns a boolean if a field has been set.
func (o *ReleaseResource) HasCustomFormatScore() bool {
	if o != nil && !isNil(o.CustomFormatScore) {
		return true
	}

	return false
}

// SetCustomFormatScore gets a reference to the given int32 and assigns it to the CustomFormatScore field.
func (o *ReleaseResource) SetCustomFormatScore(v int32) {
	o.CustomFormatScore = &v
}

// GetMagnetUrl returns the MagnetUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetMagnetUrl() string {
	if o == nil || isNil(o.MagnetUrl.Get()) {
		var ret string
		return ret
	}
	return *o.MagnetUrl.Get()
}

// GetMagnetUrlOk returns a tuple with the MagnetUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetMagnetUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.MagnetUrl.Get(), o.MagnetUrl.IsSet()
}

// HasMagnetUrl returns a boolean if a field has been set.
func (o *ReleaseResource) HasMagnetUrl() bool {
	if o != nil && o.MagnetUrl.IsSet() {
		return true
	}

	return false
}

// SetMagnetUrl gets a reference to the given NullableString and assigns it to the MagnetUrl field.
func (o *ReleaseResource) SetMagnetUrl(v string) {
	o.MagnetUrl.Set(&v)
}
// SetMagnetUrlNil sets the value for MagnetUrl to be an explicit nil
func (o *ReleaseResource) SetMagnetUrlNil() {
	o.MagnetUrl.Set(nil)
}

// UnsetMagnetUrl ensures that no value is present for MagnetUrl, not even an explicit nil
func (o *ReleaseResource) UnsetMagnetUrl() {
	o.MagnetUrl.Unset()
}

// GetInfoHash returns the InfoHash field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetInfoHash() string {
	if o == nil || isNil(o.InfoHash.Get()) {
		var ret string
		return ret
	}
	return *o.InfoHash.Get()
}

// GetInfoHashOk returns a tuple with the InfoHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetInfoHashOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.InfoHash.Get(), o.InfoHash.IsSet()
}

// HasInfoHash returns a boolean if a field has been set.
func (o *ReleaseResource) HasInfoHash() bool {
	if o != nil && o.InfoHash.IsSet() {
		return true
	}

	return false
}

// SetInfoHash gets a reference to the given NullableString and assigns it to the InfoHash field.
func (o *ReleaseResource) SetInfoHash(v string) {
	o.InfoHash.Set(&v)
}
// SetInfoHashNil sets the value for InfoHash to be an explicit nil
func (o *ReleaseResource) SetInfoHashNil() {
	o.InfoHash.Set(nil)
}

// UnsetInfoHash ensures that no value is present for InfoHash, not even an explicit nil
func (o *ReleaseResource) UnsetInfoHash() {
	o.InfoHash.Unset()
}

// GetSeeders returns the Seeders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetSeeders() int32 {
	if o == nil || isNil(o.Seeders.Get()) {
		var ret int32
		return ret
	}
	return *o.Seeders.Get()
}

// GetSeedersOk returns a tuple with the Seeders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetSeedersOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return o.Seeders.Get(), o.Seeders.IsSet()
}

// HasSeeders returns a boolean if a field has been set.
func (o *ReleaseResource) HasSeeders() bool {
	if o != nil && o.Seeders.IsSet() {
		return true
	}

	return false
}

// SetSeeders gets a reference to the given NullableInt32 and assigns it to the Seeders field.
func (o *ReleaseResource) SetSeeders(v int32) {
	o.Seeders.Set(&v)
}
// SetSeedersNil sets the value for Seeders to be an explicit nil
func (o *ReleaseResource) SetSeedersNil() {
	o.Seeders.Set(nil)
}

// UnsetSeeders ensures that no value is present for Seeders, not even an explicit nil
func (o *ReleaseResource) UnsetSeeders() {
	o.Seeders.Unset()
}

// GetLeechers returns the Leechers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetLeechers() int32 {
	if o == nil || isNil(o.Leechers.Get()) {
		var ret int32
		return ret
	}
	return *o.Leechers.Get()
}

// GetLeechersOk returns a tuple with the Leechers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetLeechersOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return o.Leechers.Get(), o.Leechers.IsSet()
}

// HasLeechers returns a boolean if a field has been set.
func (o *ReleaseResource) HasLeechers() bool {
	if o != nil && o.Leechers.IsSet() {
		return true
	}

	return false
}

// SetLeechers gets a reference to the given NullableInt32 and assigns it to the Leechers field.
func (o *ReleaseResource) SetLeechers(v int32) {
	o.Leechers.Set(&v)
}
// SetLeechersNil sets the value for Leechers to be an explicit nil
func (o *ReleaseResource) SetLeechersNil() {
	o.Leechers.Set(nil)
}

// UnsetLeechers ensures that no value is present for Leechers, not even an explicit nil
func (o *ReleaseResource) UnsetLeechers() {
	o.Leechers.Unset()
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *ReleaseResource) GetProtocol() DownloadProtocol {
	if o == nil || isNil(o.Protocol) {
		var ret DownloadProtocol
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseResource) GetProtocolOk() (*DownloadProtocol, bool) {
	if o == nil || isNil(o.Protocol) {
    return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *ReleaseResource) HasProtocol() bool {
	if o != nil && !isNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given DownloadProtocol and assigns it to the Protocol field.
func (o *ReleaseResource) SetProtocol(v DownloadProtocol) {
	o.Protocol = &v
}

// GetAuthorId returns the AuthorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetAuthorId() int32 {
	if o == nil || isNil(o.AuthorId.Get()) {
		var ret int32
		return ret
	}
	return *o.AuthorId.Get()
}

// GetAuthorIdOk returns a tuple with the AuthorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetAuthorIdOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return o.AuthorId.Get(), o.AuthorId.IsSet()
}

// HasAuthorId returns a boolean if a field has been set.
func (o *ReleaseResource) HasAuthorId() bool {
	if o != nil && o.AuthorId.IsSet() {
		return true
	}

	return false
}

// SetAuthorId gets a reference to the given NullableInt32 and assigns it to the AuthorId field.
func (o *ReleaseResource) SetAuthorId(v int32) {
	o.AuthorId.Set(&v)
}
// SetAuthorIdNil sets the value for AuthorId to be an explicit nil
func (o *ReleaseResource) SetAuthorIdNil() {
	o.AuthorId.Set(nil)
}

// UnsetAuthorId ensures that no value is present for AuthorId, not even an explicit nil
func (o *ReleaseResource) UnsetAuthorId() {
	o.AuthorId.Unset()
}

// GetBookId returns the BookId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetBookId() int32 {
	if o == nil || isNil(o.BookId.Get()) {
		var ret int32
		return ret
	}
	return *o.BookId.Get()
}

// GetBookIdOk returns a tuple with the BookId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetBookIdOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return o.BookId.Get(), o.BookId.IsSet()
}

// HasBookId returns a boolean if a field has been set.
func (o *ReleaseResource) HasBookId() bool {
	if o != nil && o.BookId.IsSet() {
		return true
	}

	return false
}

// SetBookId gets a reference to the given NullableInt32 and assigns it to the BookId field.
func (o *ReleaseResource) SetBookId(v int32) {
	o.BookId.Set(&v)
}
// SetBookIdNil sets the value for BookId to be an explicit nil
func (o *ReleaseResource) SetBookIdNil() {
	o.BookId.Set(nil)
}

// UnsetBookId ensures that no value is present for BookId, not even an explicit nil
func (o *ReleaseResource) UnsetBookId() {
	o.BookId.Unset()
}

// GetDownloadClientId returns the DownloadClientId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetDownloadClientId() int32 {
	if o == nil || isNil(o.DownloadClientId.Get()) {
		var ret int32
		return ret
	}
	return *o.DownloadClientId.Get()
}

// GetDownloadClientIdOk returns a tuple with the DownloadClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetDownloadClientIdOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return o.DownloadClientId.Get(), o.DownloadClientId.IsSet()
}

// HasDownloadClientId returns a boolean if a field has been set.
func (o *ReleaseResource) HasDownloadClientId() bool {
	if o != nil && o.DownloadClientId.IsSet() {
		return true
	}

	return false
}

// SetDownloadClientId gets a reference to the given NullableInt32 and assigns it to the DownloadClientId field.
func (o *ReleaseResource) SetDownloadClientId(v int32) {
	o.DownloadClientId.Set(&v)
}
// SetDownloadClientIdNil sets the value for DownloadClientId to be an explicit nil
func (o *ReleaseResource) SetDownloadClientIdNil() {
	o.DownloadClientId.Set(nil)
}

// UnsetDownloadClientId ensures that no value is present for DownloadClientId, not even an explicit nil
func (o *ReleaseResource) UnsetDownloadClientId() {
	o.DownloadClientId.Unset()
}

// GetDownloadClient returns the DownloadClient field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseResource) GetDownloadClient() string {
	if o == nil || isNil(o.DownloadClient.Get()) {
		var ret string
		return ret
	}
	return *o.DownloadClient.Get()
}

// GetDownloadClientOk returns a tuple with the DownloadClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseResource) GetDownloadClientOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.DownloadClient.Get(), o.DownloadClient.IsSet()
}

// HasDownloadClient returns a boolean if a field has been set.
func (o *ReleaseResource) HasDownloadClient() bool {
	if o != nil && o.DownloadClient.IsSet() {
		return true
	}

	return false
}

// SetDownloadClient gets a reference to the given NullableString and assigns it to the DownloadClient field.
func (o *ReleaseResource) SetDownloadClient(v string) {
	o.DownloadClient.Set(&v)
}
// SetDownloadClientNil sets the value for DownloadClient to be an explicit nil
func (o *ReleaseResource) SetDownloadClientNil() {
	o.DownloadClient.Set(nil)
}

// UnsetDownloadClient ensures that no value is present for DownloadClient, not even an explicit nil
func (o *ReleaseResource) UnsetDownloadClient() {
	o.DownloadClient.Unset()
}

func (o ReleaseResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Guid.IsSet() {
		toSerialize["guid"] = o.Guid.Get()
	}
	if !isNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	if !isNil(o.QualityWeight) {
		toSerialize["qualityWeight"] = o.QualityWeight
	}
	if !isNil(o.Age) {
		toSerialize["age"] = o.Age
	}
	if !isNil(o.AgeHours) {
		toSerialize["ageHours"] = o.AgeHours
	}
	if !isNil(o.AgeMinutes) {
		toSerialize["ageMinutes"] = o.AgeMinutes
	}
	if !isNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !isNil(o.IndexerId) {
		toSerialize["indexerId"] = o.IndexerId
	}
	if o.Indexer.IsSet() {
		toSerialize["indexer"] = o.Indexer.Get()
	}
	if o.ReleaseGroup.IsSet() {
		toSerialize["releaseGroup"] = o.ReleaseGroup.Get()
	}
	if o.SubGroup.IsSet() {
		toSerialize["subGroup"] = o.SubGroup.Get()
	}
	if o.ReleaseHash.IsSet() {
		toSerialize["releaseHash"] = o.ReleaseHash.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if !isNil(o.Discography) {
		toSerialize["discography"] = o.Discography
	}
	if !isNil(o.SceneSource) {
		toSerialize["sceneSource"] = o.SceneSource
	}
	if o.AirDate.IsSet() {
		toSerialize["airDate"] = o.AirDate.Get()
	}
	if o.AuthorName.IsSet() {
		toSerialize["authorName"] = o.AuthorName.Get()
	}
	if o.BookTitle.IsSet() {
		toSerialize["bookTitle"] = o.BookTitle.Get()
	}
	if !isNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	if !isNil(o.TemporarilyRejected) {
		toSerialize["temporarilyRejected"] = o.TemporarilyRejected
	}
	if !isNil(o.Rejected) {
		toSerialize["rejected"] = o.Rejected
	}
	if o.Rejections != nil {
		toSerialize["rejections"] = o.Rejections
	}
	if !isNil(o.PublishDate) {
		toSerialize["publishDate"] = o.PublishDate
	}
	if o.CommentUrl.IsSet() {
		toSerialize["commentUrl"] = o.CommentUrl.Get()
	}
	if o.DownloadUrl.IsSet() {
		toSerialize["downloadUrl"] = o.DownloadUrl.Get()
	}
	if o.InfoUrl.IsSet() {
		toSerialize["infoUrl"] = o.InfoUrl.Get()
	}
	if !isNil(o.DownloadAllowed) {
		toSerialize["downloadAllowed"] = o.DownloadAllowed
	}
	if !isNil(o.ReleaseWeight) {
		toSerialize["releaseWeight"] = o.ReleaseWeight
	}
	if o.CustomFormats != nil {
		toSerialize["customFormats"] = o.CustomFormats
	}
	if !isNil(o.CustomFormatScore) {
		toSerialize["customFormatScore"] = o.CustomFormatScore
	}
	if o.MagnetUrl.IsSet() {
		toSerialize["magnetUrl"] = o.MagnetUrl.Get()
	}
	if o.InfoHash.IsSet() {
		toSerialize["infoHash"] = o.InfoHash.Get()
	}
	if o.Seeders.IsSet() {
		toSerialize["seeders"] = o.Seeders.Get()
	}
	if o.Leechers.IsSet() {
		toSerialize["leechers"] = o.Leechers.Get()
	}
	if !isNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if o.AuthorId.IsSet() {
		toSerialize["authorId"] = o.AuthorId.Get()
	}
	if o.BookId.IsSet() {
		toSerialize["bookId"] = o.BookId.Get()
	}
	if o.DownloadClientId.IsSet() {
		toSerialize["downloadClientId"] = o.DownloadClientId.Get()
	}
	if o.DownloadClient.IsSet() {
		toSerialize["downloadClient"] = o.DownloadClient.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableReleaseResource struct {
	value *ReleaseResource
	isSet bool
}

func (v NullableReleaseResource) Get() *ReleaseResource {
	return v.value
}

func (v *NullableReleaseResource) Set(val *ReleaseResource) {
	v.value = val
	v.isSet = true
}

func (v NullableReleaseResource) IsSet() bool {
	return v.isSet
}

func (v *NullableReleaseResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReleaseResource(val *ReleaseResource) *NullableReleaseResource {
	return &NullableReleaseResource{value: val, isSet: true}
}

func (v NullableReleaseResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReleaseResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


