/*
Readarr

Readarr API docs

API version: v0.3.18.2411
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package readarr

import (
	"encoding/json"
)

// checks if the BookStatisticsResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookStatisticsResource{}

// BookStatisticsResource struct for BookStatisticsResource
type BookStatisticsResource struct {
	BookFileCount *int32 `json:"bookFileCount,omitempty"`
	BookCount *int32 `json:"bookCount,omitempty"`
	TotalBookCount *int32 `json:"totalBookCount,omitempty"`
	SizeOnDisk *int64 `json:"sizeOnDisk,omitempty"`
	PercentOfBooks *float64 `json:"percentOfBooks,omitempty"`
}

// NewBookStatisticsResource instantiates a new BookStatisticsResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookStatisticsResource() *BookStatisticsResource {
	this := BookStatisticsResource{}
	return &this
}

// NewBookStatisticsResourceWithDefaults instantiates a new BookStatisticsResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookStatisticsResourceWithDefaults() *BookStatisticsResource {
	this := BookStatisticsResource{}
	return &this
}

// GetBookFileCount returns the BookFileCount field value if set, zero value otherwise.
func (o *BookStatisticsResource) GetBookFileCount() int32 {
	if o == nil || IsNil(o.BookFileCount) {
		var ret int32
		return ret
	}
	return *o.BookFileCount
}

// GetBookFileCountOk returns a tuple with the BookFileCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookStatisticsResource) GetBookFileCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BookFileCount) {
		return nil, false
	}
	return o.BookFileCount, true
}

// HasBookFileCount returns a boolean if a field has been set.
func (o *BookStatisticsResource) HasBookFileCount() bool {
	if o != nil && !IsNil(o.BookFileCount) {
		return true
	}

	return false
}

// SetBookFileCount gets a reference to the given int32 and assigns it to the BookFileCount field.
func (o *BookStatisticsResource) SetBookFileCount(v int32) {
	o.BookFileCount = &v
}

// GetBookCount returns the BookCount field value if set, zero value otherwise.
func (o *BookStatisticsResource) GetBookCount() int32 {
	if o == nil || IsNil(o.BookCount) {
		var ret int32
		return ret
	}
	return *o.BookCount
}

// GetBookCountOk returns a tuple with the BookCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookStatisticsResource) GetBookCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BookCount) {
		return nil, false
	}
	return o.BookCount, true
}

// HasBookCount returns a boolean if a field has been set.
func (o *BookStatisticsResource) HasBookCount() bool {
	if o != nil && !IsNil(o.BookCount) {
		return true
	}

	return false
}

// SetBookCount gets a reference to the given int32 and assigns it to the BookCount field.
func (o *BookStatisticsResource) SetBookCount(v int32) {
	o.BookCount = &v
}

// GetTotalBookCount returns the TotalBookCount field value if set, zero value otherwise.
func (o *BookStatisticsResource) GetTotalBookCount() int32 {
	if o == nil || IsNil(o.TotalBookCount) {
		var ret int32
		return ret
	}
	return *o.TotalBookCount
}

// GetTotalBookCountOk returns a tuple with the TotalBookCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookStatisticsResource) GetTotalBookCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalBookCount) {
		return nil, false
	}
	return o.TotalBookCount, true
}

// HasTotalBookCount returns a boolean if a field has been set.
func (o *BookStatisticsResource) HasTotalBookCount() bool {
	if o != nil && !IsNil(o.TotalBookCount) {
		return true
	}

	return false
}

// SetTotalBookCount gets a reference to the given int32 and assigns it to the TotalBookCount field.
func (o *BookStatisticsResource) SetTotalBookCount(v int32) {
	o.TotalBookCount = &v
}

// GetSizeOnDisk returns the SizeOnDisk field value if set, zero value otherwise.
func (o *BookStatisticsResource) GetSizeOnDisk() int64 {
	if o == nil || IsNil(o.SizeOnDisk) {
		var ret int64
		return ret
	}
	return *o.SizeOnDisk
}

// GetSizeOnDiskOk returns a tuple with the SizeOnDisk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookStatisticsResource) GetSizeOnDiskOk() (*int64, bool) {
	if o == nil || IsNil(o.SizeOnDisk) {
		return nil, false
	}
	return o.SizeOnDisk, true
}

// HasSizeOnDisk returns a boolean if a field has been set.
func (o *BookStatisticsResource) HasSizeOnDisk() bool {
	if o != nil && !IsNil(o.SizeOnDisk) {
		return true
	}

	return false
}

// SetSizeOnDisk gets a reference to the given int64 and assigns it to the SizeOnDisk field.
func (o *BookStatisticsResource) SetSizeOnDisk(v int64) {
	o.SizeOnDisk = &v
}

// GetPercentOfBooks returns the PercentOfBooks field value if set, zero value otherwise.
func (o *BookStatisticsResource) GetPercentOfBooks() float64 {
	if o == nil || IsNil(o.PercentOfBooks) {
		var ret float64
		return ret
	}
	return *o.PercentOfBooks
}

// GetPercentOfBooksOk returns a tuple with the PercentOfBooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BookStatisticsResource) GetPercentOfBooksOk() (*float64, bool) {
	if o == nil || IsNil(o.PercentOfBooks) {
		return nil, false
	}
	return o.PercentOfBooks, true
}

// HasPercentOfBooks returns a boolean if a field has been set.
func (o *BookStatisticsResource) HasPercentOfBooks() bool {
	if o != nil && !IsNil(o.PercentOfBooks) {
		return true
	}

	return false
}

// SetPercentOfBooks gets a reference to the given float64 and assigns it to the PercentOfBooks field.
func (o *BookStatisticsResource) SetPercentOfBooks(v float64) {
	o.PercentOfBooks = &v
}

func (o BookStatisticsResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookStatisticsResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BookFileCount) {
		toSerialize["bookFileCount"] = o.BookFileCount
	}
	if !IsNil(o.BookCount) {
		toSerialize["bookCount"] = o.BookCount
	}
	if !IsNil(o.TotalBookCount) {
		toSerialize["totalBookCount"] = o.TotalBookCount
	}
	if !IsNil(o.SizeOnDisk) {
		toSerialize["sizeOnDisk"] = o.SizeOnDisk
	}
	if !IsNil(o.PercentOfBooks) {
		toSerialize["percentOfBooks"] = o.PercentOfBooks
	}
	return toSerialize, nil
}

type NullableBookStatisticsResource struct {
	value *BookStatisticsResource
	isSet bool
}

func (v NullableBookStatisticsResource) Get() *BookStatisticsResource {
	return v.value
}

func (v *NullableBookStatisticsResource) Set(val *BookStatisticsResource) {
	v.value = val
	v.isSet = true
}

func (v NullableBookStatisticsResource) IsSet() bool {
	return v.isSet
}

func (v *NullableBookStatisticsResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookStatisticsResource(val *BookStatisticsResource) *NullableBookStatisticsResource {
	return &NullableBookStatisticsResource{value: val, isSet: true}
}

func (v NullableBookStatisticsResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookStatisticsResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


