/*
Readarr

Readarr API docs

API version: v0.3.18.2411
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package readarr

import (
	"encoding/json"
)

// checks if the AddAuthorOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAuthorOptions{}

// AddAuthorOptions struct for AddAuthorOptions
type AddAuthorOptions struct {
	Monitor *MonitorTypes `json:"monitor,omitempty"`
	BooksToMonitor []string `json:"booksToMonitor,omitempty"`
	Monitored *bool `json:"monitored,omitempty"`
	SearchForMissingBooks *bool `json:"searchForMissingBooks,omitempty"`
}

// NewAddAuthorOptions instantiates a new AddAuthorOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAuthorOptions() *AddAuthorOptions {
	this := AddAuthorOptions{}
	return &this
}

// NewAddAuthorOptionsWithDefaults instantiates a new AddAuthorOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAuthorOptionsWithDefaults() *AddAuthorOptions {
	this := AddAuthorOptions{}
	return &this
}

// GetMonitor returns the Monitor field value if set, zero value otherwise.
func (o *AddAuthorOptions) GetMonitor() MonitorTypes {
	if o == nil || IsNil(o.Monitor) {
		var ret MonitorTypes
		return ret
	}
	return *o.Monitor
}

// GetMonitorOk returns a tuple with the Monitor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAuthorOptions) GetMonitorOk() (*MonitorTypes, bool) {
	if o == nil || IsNil(o.Monitor) {
		return nil, false
	}
	return o.Monitor, true
}

// HasMonitor returns a boolean if a field has been set.
func (o *AddAuthorOptions) HasMonitor() bool {
	if o != nil && !IsNil(o.Monitor) {
		return true
	}

	return false
}

// SetMonitor gets a reference to the given MonitorTypes and assigns it to the Monitor field.
func (o *AddAuthorOptions) SetMonitor(v MonitorTypes) {
	o.Monitor = &v
}

// GetBooksToMonitor returns the BooksToMonitor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddAuthorOptions) GetBooksToMonitor() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.BooksToMonitor
}

// GetBooksToMonitorOk returns a tuple with the BooksToMonitor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddAuthorOptions) GetBooksToMonitorOk() ([]string, bool) {
	if o == nil || IsNil(o.BooksToMonitor) {
		return nil, false
	}
	return o.BooksToMonitor, true
}

// HasBooksToMonitor returns a boolean if a field has been set.
func (o *AddAuthorOptions) HasBooksToMonitor() bool {
	if o != nil && IsNil(o.BooksToMonitor) {
		return true
	}

	return false
}

// SetBooksToMonitor gets a reference to the given []string and assigns it to the BooksToMonitor field.
func (o *AddAuthorOptions) SetBooksToMonitor(v []string) {
	o.BooksToMonitor = v
}

// GetMonitored returns the Monitored field value if set, zero value otherwise.
func (o *AddAuthorOptions) GetMonitored() bool {
	if o == nil || IsNil(o.Monitored) {
		var ret bool
		return ret
	}
	return *o.Monitored
}

// GetMonitoredOk returns a tuple with the Monitored field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAuthorOptions) GetMonitoredOk() (*bool, bool) {
	if o == nil || IsNil(o.Monitored) {
		return nil, false
	}
	return o.Monitored, true
}

// HasMonitored returns a boolean if a field has been set.
func (o *AddAuthorOptions) HasMonitored() bool {
	if o != nil && !IsNil(o.Monitored) {
		return true
	}

	return false
}

// SetMonitored gets a reference to the given bool and assigns it to the Monitored field.
func (o *AddAuthorOptions) SetMonitored(v bool) {
	o.Monitored = &v
}

// GetSearchForMissingBooks returns the SearchForMissingBooks field value if set, zero value otherwise.
func (o *AddAuthorOptions) GetSearchForMissingBooks() bool {
	if o == nil || IsNil(o.SearchForMissingBooks) {
		var ret bool
		return ret
	}
	return *o.SearchForMissingBooks
}

// GetSearchForMissingBooksOk returns a tuple with the SearchForMissingBooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAuthorOptions) GetSearchForMissingBooksOk() (*bool, bool) {
	if o == nil || IsNil(o.SearchForMissingBooks) {
		return nil, false
	}
	return o.SearchForMissingBooks, true
}

// HasSearchForMissingBooks returns a boolean if a field has been set.
func (o *AddAuthorOptions) HasSearchForMissingBooks() bool {
	if o != nil && !IsNil(o.SearchForMissingBooks) {
		return true
	}

	return false
}

// SetSearchForMissingBooks gets a reference to the given bool and assigns it to the SearchForMissingBooks field.
func (o *AddAuthorOptions) SetSearchForMissingBooks(v bool) {
	o.SearchForMissingBooks = &v
}

func (o AddAuthorOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAuthorOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Monitor) {
		toSerialize["monitor"] = o.Monitor
	}
	if o.BooksToMonitor != nil {
		toSerialize["booksToMonitor"] = o.BooksToMonitor
	}
	if !IsNil(o.Monitored) {
		toSerialize["monitored"] = o.Monitored
	}
	if !IsNil(o.SearchForMissingBooks) {
		toSerialize["searchForMissingBooks"] = o.SearchForMissingBooks
	}
	return toSerialize, nil
}

type NullableAddAuthorOptions struct {
	value *AddAuthorOptions
	isSet bool
}

func (v NullableAddAuthorOptions) Get() *AddAuthorOptions {
	return v.value
}

func (v *NullableAddAuthorOptions) Set(val *AddAuthorOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAuthorOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAuthorOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAuthorOptions(val *AddAuthorOptions) *NullableAddAuthorOptions {
	return &NullableAddAuthorOptions{value: val, isSet: true}
}

func (v NullableAddAuthorOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAuthorOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


